import { readdir, readFile, stat, writeFile } from "node:fs/promises";
import { extname, join, relative, resolve, sep } from "node:path";

const root = resolve("dist");
const output = resolve("worker/embedded-site.ts");
const contentTypes = {
  ".css": "text/css; charset=utf-8",
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".txt": "text/plain; charset=utf-8",
  ".xml": "application/xml; charset=utf-8",
};

async function files(directory) {
  const entries = await readdir(directory);
  const nested = await Promise.all(entries.map(async (entry) => {
    const path = join(directory, entry);
    return (await stat(path)).isDirectory() ? files(path) : [path];
  }));
  return nested.flat();
}

const assets = {};
for (const path of await files(root)) {
  const pathname = `/${relative(root, path).split(sep).join("/")}`;
  const contentType = contentTypes[extname(path)] || "application/octet-stream";
  const buffer = await readFile(path);
  assets[pathname] = {
    contentType,
    body: contentType === "application/octet-stream" ? buffer.toString("base64") : buffer.toString("utf8"),
  };
}

await writeFile(
  output,
  `// Generated by scripts/embed-site.mjs during \`npm run build\`.\nexport const EMBEDDED_SITE: Record<string, { contentType: string; body: string }> = ${JSON.stringify(assets)};\n`,
  "utf8",
);
